### Add a new contact to the DB.
POST http://localhost:8080/api/contact/add
content-type: application/json

{
  "name": "Arif Yakoob",
  "emailId": "arif2@gmail.com",
  "phoneNumber": 98134565431
}

### Get all the users
GET http://localhost:8080/api/contact/all
content-type: application/json

### Update the contact details
PUT http://localhost:8080/api/contact/update/6198ce70c290c312780f228f
Content-Type: application/json

{
  "name": "Arif Yakoob",
  "emailId": "arif_updated1@gmail.com",
  "phoneNumber": 1234567789
}

### Delete the contact details
DELETE http://localhost:8080/api/contact/delete/6198ce9ec290c312780f2294
Content-Type: application/json
