### Add a new contact to the DB.
POST http://localhost:8080/api/contact/add
content-type: application/json

{
  "name": "Arif Yakoob",
  "emailId": "arif3@gmail.com",
  "phoneNumber": 9834565432
}

### Get all the users
GET http://localhost:8080/api/contact/all
content-type: application/json

### Update the contact details
PUT http://localhost:8080/api/contact/update/61980fd84ccf3df36ad017c5
Content-Type: application/json

{
  "name": "Arif Yakoob",
  "emailId": "arif_updated1@gmail.com",
  "phoneNumber": 1234567789
}

### Delete the contact details
DELETE http://localhost:8080/api/contact/delete/61986b8abf8577c1f43806aa
Content-Type: application/json
